### ISSUE TITLE
itemtype small icon disappears when filter active if it is not an svg icon

### ISSUE THREAD

**Issue by YoannArasLab** [ArasLabs/toc-search-bar#2]
Here is an exemple with an image stored in the codetree
![image](https://user-images.githubusercontent.com/22646995/35704975-670b30d4-07a1-11e8-84c5-d521b0745f57.png)

And here is the result when filtered

![image](https://user-images.githubusercontent.com/22646995/35705071-aa4e0542-07a1-11e8-9590-1ed80a6b0475.png)

**Comment by cgillis-aras** [comment]
Fixed in Pull Request : "Fixed default close and missing icons #4"
